version: '2'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

  backend:
    container_name: backend
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - default
    environment:
      - PORT=8888
      - NODE_ENV=development
      - POSTGRES_HOST=db
    ports:
      - 8888:8888

volumes:
  pgdata:

networks:
  default:
